**This notebook is an exercise in the [Pandas](https://www.kaggle.com/learn/pandas) course.  You can reference the tutorial at [this link](https://www.kaggle.com/residentmario/grouping-and-sorting).**

---

# Introduction

In these exercises we'll apply groupwise analysis to our dataset.

Run the code cell below to load the data before running the exercises.

In [1]:
import pandas as pd

reviews = pd.read_csv(r"c:\Users\Shamit\Downloads\winemag-data-130k-v2.csv", index_col=0)
pd.set_option("display.max_rows", 5)
#from learntools.core import binder; binder.bind(globals())
#from learntools.pandas.grouping_and_sorting import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [2]:
# Your code here
reviews_written = reviews['taster_twitter_handle'].value_counts()
# Check your answer
#q1.check()
reviews_written

taster_twitter_handle
@vossroger         13045
@wineschach         7752
                   ...
@bkfiona              11
@winewchristina        4
Name: count, Length: 15, dtype: int64

In [ ]:
#q1.hint()
#q1.solution()

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [4]:
best_rating_per_price = reviews.groupby('price')['points'].max().sort_index()
# Check your answer
#q2.check()
best_rating_per_price

price
4.0       86
5.0       87
          ..
2000.0    97
2500.0    96
Name: points, Length: 312, dtype: int64

In [ ]:
#q2.hint()
#q2.solution()

## 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [5]:
price_extremes = reviews.groupby('variety')['price'].agg(['min', 'max'])
price_extremes.columns = ['min_price', 'max_price']
# Check your answer
#q3.check()
price_extremes

             min_price  max_price
variety
Abouriou          75.0       75.0
Agiorgitiko       10.0       66.0
...                ...        ...
Çalkarası         19.0       19.0
Žilavka           15.0       15.0

[590 rows x 2 columns]

In [ ]:
#q3.hint()
#q3.solution()

## 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [10]:
price_extremes = reviews.groupby('variety')['price'].agg(['min', 'max'])
price_extremes.columns = ['min_price', 'max_price']
sorted_varieties = price_extremes.sort_values(by=['min_price', 'max_price'], ascending=[False, False]).copy()
# Check your answer
#q4.check()
sorted_varieties

                    min_price  max_price
variety
Terrantez               236.0      236.0
Bual                    194.0      230.0
...                       ...        ...
Tempranillo-Malbec        NaN        NaN
Zelen                     NaN        NaN

[590 rows x 2 columns]

In [ ]:
#q4.hint()
#q4.solution()

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [12]:
reviewer_mean_ratings = reviews.groupby('taster_name')['points'].mean()
# Check your answer
#q5.check()
reviewer_mean_ratings

taster_name
Alexander Peartree    86.014286
Anna Lee C. Iijima    88.380506
                        ...
Susan Kostrzewa       86.408094
Virginie Boone        89.229557
Name: points, Length: 19, dtype: float64

In [ ]:
#q5.hint()
#q5.solution()

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [13]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.332052
           ...
75%      89.062667
max      90.587903
Name: points, Length: 8, dtype: float64

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [14]:
country_variety_counts = reviews.groupby(['country', 'variety']).size()
country_variety_counts = country_variety_counts.sort_values(ascending=False)
# Check your answer
#q6.check()
country_variety_counts

country  variety
US       Pinot Noir            4918
         Cabernet Sauvignon    3649
                               ...
Italy    Vitovska                 1
Uruguay  Tempranillo-Tannat       1
Length: 1304, dtype: int64

In [ ]:
#q6.hint()
#q6.solution()

# Keep going

Move on to the [**data types and missing data**](https://www.kaggle.com/residentmario/data-types-and-missing-values).

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/pandas/discussion) to chat with other learners.*